### PR TITLE
Formatting fix and https fix for sra toolkit download

### PR DESCRIPTION
**Pull request by amanjeev**
Hi @bmpvieira ! I made some minor changes to the repo. It fails to be installed because the url for SRA toolkit download was http. so I updates the Makefile.

I also formatted the code a bit.

### CODE REVIEW

**Comment by bmpvieira** [comment]
Hey @amanjeev ! Thanks for the PR!! Would you just mind to follow the [standardjs.com](http://standardjs.com) style?

Cheers,
Bruno

**Comment by amanjeev** [comment]
Sure. Thanks for taking a look. Let me fix that and update the PR. Give me some time though.

**Comment by amanjeev** [comment]
Sorry it took longer than usual for merely formatting the code. Should be good now. I just used `standard --fix`.

**Comment by bmpvieira** [comment]
No problem @amanjeev! One last thing, could you undo the changes to the comments? Those comments are formatted that way and used to generate the documentation with ```npm run build-docs```. Thank you!

**Comment by amanjeev** [comment]
Sorry about this fiasco! I've reset the entire branch and just made the relevant changes. Now only two commits, what it should have been in the beginning anyway. :)

**Comment by bmpvieira** [comment]
ahah don't worry, next time will be better! :)

**Comment by amanjeev** [comment]
Thank you for allowing me to participate!

**Pull request merged**
